;;;; tests.lisp
;;;;
;;;; Aggregate test system.  Every test package must be listed here; the
;;;; PERFORM :AFTER method below derives the packages to run from the inferred
;;;; dependency list, so an unlisted test file is silently never run.

(defpackage #:cl-spec/tests
  (:use #:cl)
  (:import-from #:rove)
  (:import-from #:cl-spec/tests/instrument-binding-test)
  (:import-from #:cl-spec/tests/return-values-schema-test)
  (:import-from #:cl-spec/tests/multiple-values-function-test)
  (:import-from #:cl-spec/tests/multiple-values-instrument-test)
  (:import-from #:cl-spec/tests/multiple-values-evidence-test)
  (:import-from #:cl-spec/tests/rest-call-schema-test)
  (:import-from #:cl-spec/tests/rest-function-test)
  (:import-from #:cl-spec/tests/rest-generator-test)
  (:import-from #:cl-spec/tests/rest-instrument-test)
  (:import-from #:cl-spec/tests/key-call-schema-test)
  (:import-from #:cl-spec/tests/key-function-test)
  (:import-from #:cl-spec/tests/key-generator-test)
  (:import-from #:cl-spec/tests/key-instrument-test)
  (:import-from #:cl-spec/tests/optional-call-schema-test)
  (:import-from #:cl-spec/tests/optional-function-test)
  (:import-from #:cl-spec/tests/optional-generator-test)
  (:import-from #:cl-spec/tests/optional-instrument-test)
  (:import-from #:cl-spec/tests/observed-outcome-test)
  (:import-from #:cl-spec/tests/call-schema-test)
  (:import-from #:cl-spec/tests/call-outcome-test)
  (:import-from #:cl-spec/tests/function-outcome-test)
  (:import-from #:cl-spec/tests/instrument-outcome-test)
  (:import-from #:cl-spec/tests/shrink-report-test)
  (:import-from #:cl-spec/tests/custom-shrinker-definition-test)
  (:import-from #:cl-spec/tests/custom-shrinker-test)
  (:import-from #:cl-spec/tests/digest-details-test)
  (:import-from #:cl-spec/tests/instrument-digest-details-test)
  (:import-from #:cl-spec/tests/function-invariants-test)
  (:import-from #:cl-spec/tests/definition-validation-test)
  (:import-from #:cl-spec/tests/generator-invariants-test)
  (:import-from #:cl-spec/tests/utils/artifact-values-test)
  (:import-from #:cl-spec/tests/result-provenance-test)
  (:import-from #:cl-spec/tests/counterexample-test)
  (:import-from #:cl-spec/tests/counterexample-function-test)
  (:import-from #:cl-spec/tests/conditions-test)
  (:import-from #:cl-spec/tests/utils/source-location-test)
  (:import-from #:cl-spec/tests/utils/random-test)
  (:import-from #:cl-spec/tests/ir-test)
  (:import-from #:cl-spec/tests/registry-test)
  (:import-from #:cl-spec/tests/resolve-test)
  (:import-from #:cl-spec/tests/normalize-test)
  (:import-from #:cl-spec/tests/plist-test)
  (:import-from #:cl-spec/tests/field-representations-test)
  (:import-from #:cl-spec/tests/object-fields-test)
  (:import-from #:cl-spec/tests/tagged-union-test)
  (:import-from #:cl-spec/tests/collection-constraints-test)
  (:import-from #:cl-spec/tests/validator-test)
  (:import-from #:cl-spec/tests/explain-test)
  (:import-from #:cl-spec/tests/generator-test)
  (:import-from #:cl-spec/tests/property-test)
  (:import-from #:cl-spec/tests/property-runner-test)
  (:import-from #:cl-spec/tests/function-spec-test)
  (:import-from #:cl-spec/tests/signals-test)
  (:import-from #:cl-spec/tests/verification-evidence-test)
  (:import-from #:cl-spec/tests/argument-generator-test)
  (:import-from #:cl-spec/tests/introspection-test)
  (:import-from #:cl-spec/tests/schema-test)
  (:import-from #:cl-spec/tests/dsl-test)
  (:import-from #:cl-spec/tests/main-test)
  (:import-from #:cl-spec/tests/api-docs-test)
  (:import-from #:cl-spec/tests/backends/check-it-test)
  (:import-from #:cl-spec/tests/backends/plist-generator-test)
  (:import-from #:cl-spec/tests/backends/keyed-generator-test)
  (:import-from #:cl-spec/tests/backends/object-generator-test)
  (:import-from #:cl-spec/tests/backends/tagged-union-generator-test)
  (:import-from #:cl-spec/tests/backends/and-generation-test)
  (:import-from #:cl-spec/tests/examples-test)
  (:import-from #:cl-spec/tests/function-cases-test)
  (:import-from #:cl-spec/tests/function-spec-cases-example-test)
  (:import-from #:cl-spec/tests/self-specs-test)
  (:import-from #:cl-spec/tests/self-properties-test)
  (:import-from #:cl-spec/tests/self-api-contracts-test)
  (:import-from #:cl-spec/tests/stateful-withdraw-example-test)
  (:import-from #:cl-spec/tests/state-observation-test)
  (:import-from #:cl-spec/tests/check-call-test)
  (:import-from #:cl-spec/tests/instrument-status-integration-test)
  (:import-from #:cl-spec/tests/instrument-test)
  (:import-from #:cl-spec/tests/instrument-status-test))

(in-package #:cl-spec/tests)

(defmethod asdf:perform :after ((op asdf:test-op)
                                (system (eql (asdf:find-system :cl-spec/tests))))
  (let ((test-packages (remove-if-not
                        (lambda (dependency)
                          (and (stringp dependency)
                               (uiop:string-prefix-p "cl-spec/tests/" dependency)))
                        (asdf:system-depends-on system))))
    (rove:run test-packages)))
