;;;; tests/custom-shrinker-test.lisp
(defpackage #:cl-spec/tests/custom-shrinker-test
  (:use #:cl)
  (:import-from #:rove #:deftest #:ok)
  (:import-from #:cl-spec/src/backends/check-it #:check-it-backend)
  (:import-from #:cl-spec/src/generator #:run-generated-test)
  (:import-from #:cl-spec/src/normalize #:normalize-spec-form)
  (:import-from #:cl-spec/src/function-spec #:function-spec #:make-function-check-property)
  (:import-from #:cl-spec/src/generator-definition #:custom-generator #:register-generator)
  (:import-from #:cl-spec/src/registry #:make-hash-table-registry)
  (:import-from #:cl-spec/src/execution #:trial-observation-arguments)
  (:import-from #:cl-spec/src/utils/random #:seed->random-state))
(in-package #:cl-spec/tests/custom-shrinker-test)

(defvar *calls* nil)
(defvar *pre-calls* 0)

(defun interval-target (lo hi point)
  (push (list lo hi point) *calls*)
  (when (= lo 99) (error "Different failure"))
  (if (= (- hi lo) 1) 42 "wrong return"))

(defun interval-pre (lo hi point)
  (incf *pre-calls*)
  (<= lo point (1- hi)))

(defun mutating-list-target (value)
  (when (= (first value) 1) (setf (first value) -1))
  "wrong return")

(deftest correlated-search-preserves-failure-and-counts-every-candidate
  (let ((*calls* nil) (*pre-calls* 0))
    (let* ((result
             (run-case
              (lambda () '(10 100 50))
              (lambda (current)
                (if (equal current '(0 2 1))
                    '((10 100 50) (0 2 1))
                    '(#(0 2 1) (bad 2 1) (0 0 0) (0 1 0) (99 100 99) (10 100 50) (0 2 1))))))
           (report (getf result :shrink-report)))
      (ok (equal '(10 100 50)
                 (trial-observation-arguments (getf result :failure))))
      (ok (getf result :shrunk-failure))
      (when (getf result :shrunk-failure)
        (ok (equal '(0 2 1) (trial-observation-arguments (getf result :shrunk-failure)))))
      (ok (eq :used (getf result :shrunk-outcome)))
      (ok (eq :available (getf (getf result :capabilities) :shrinking)))
      (ok (= 9 (getf report :candidates -1)))
      (ok (eq :exhausted (getf report :termination)))
      (ok (= 4 (length *calls*)))
      (ok (= 5 *pre-calls*)))))

(deftest budgets-stop-before-draws-or-shrinker-invocations
  (let ((draws 0) (shrinks 0) (*calls* nil) (*pre-calls* 0))
    (dolist (budget '(-1 100001 bad))
      (ok (handler-case
              (progn (run-case (lambda () (incf draws) '(10 100 50)) nil :budget budget) nil)
            (type-error () t))))
    (ok (zerop draws))
    (let ((result (run-case (lambda () (incf draws) '(10 100 50))
                            (lambda (current) (declare (ignore current)) (incf shrinks) nil)
                            :budget 0)))
      (ok (= 1 draws))
      (ok (zerop shrinks))
      (ok (null (getf result :shrunk-failure)))
      (ok (equal '(:candidates 0 :budget 0 :termination :budget-exhausted)
                 (getf result :shrink-report))))))

(deftest malformed-and-overbudget-candidate-lists-never-reach-target
  (let ((cycle (list '(0 2 1))) (*calls* nil) (*pre-calls* 0))
    (setf (cdr cycle) cycle)
    (dolist (candidates (list cycle '((0 2 1) . bad)))
      (setf *calls* nil)
      (let ((result (run-case (lambda () '(10 100 50))
                              (lambda (current) (declare (ignore current)) candidates))))
        (ok (eq :invalid-candidates (getf (getf result :shrink-report) :termination)))
        (ok (null (getf result :shrunk-failure)))
        (ok (= 1 (length *calls*)))))
    (setf *calls* nil)
    (let ((result (run-case (lambda () '(10 100 50))
                            (lambda (current) (declare (ignore current)) '((0 2 1) (0 1 0)))
                            :budget 1)))
      (ok (eq :budget-exhausted (getf (getf result :shrink-report) :termination)))
      (ok (= 1 (getf (getf result :shrink-report) :candidates)))
      (ok (= 1 (length *calls*))))))

(deftest shrinker-errors-retain-previous-accepted-evidence
  (let ((*calls* nil) (*pre-calls* 0))
    (let ((result (run-case (lambda () '(10 100 50))
                            (lambda (current)
                              (if (equal current '(0 2 1)) (error "shrinker failed")
                                  '((0 2 1)))))))
      (ok (eq :shrinker-error (getf (getf result :shrink-report) :termination)))
      (ok (getf result :shrunk-failure))
      (when (getf result :shrunk-failure)
        (ok (equal '(0 2 1) (trial-observation-arguments (getf result :shrunk-failure)))))
      (ok (equal '(10 100 50) (trial-observation-arguments (getf result :failure)))))))

(deftest mutation-stops-without-recording-mutated-evidence
  (let ((*calls* nil) (*pre-calls* 0))
    (let ((result (run-case (lambda () '(10 100 50))
                            (lambda (current) (setf (first current) 0) '((0 2 1))))))
      (ok (eq :mutation (getf (getf result :shrink-report) :termination)))
      (ok (null (getf result :shrunk-failure)))
      (ok (equal '(10 100 50) (trial-observation-arguments (getf result :failure)))))
    (let ((result (run-case (lambda () '((10 20)))
                            (lambda (current)
                              (if (= 10 (first (first current))) '(((5 6))) '(((1 2)))))
                            :target 'mutating-list-target :arguments '((value (list-of integer)))
                            :pre nil)))
      (ok (eq :mutation (getf (getf result :shrink-report) :termination)))
      (ok (getf result :shrunk-failure))
      (when (getf result :shrunk-failure)
        (ok (equal '((5 6)) (trial-observation-arguments (getf result :shrunk-failure)))))
      (ok (equal '((10 20)) (trial-observation-arguments (getf result :failure)))))))

(deftest custom-search-replays-and-pins-check-it-size
  (flet ((once ()
           (let ((*calls* nil) (*pre-calls* 0))
             (let ((result
                     (run-case (lambda () (list 10 (+ 100 (random 100)) 50))
                               (lambda (current)
                                 (declare (ignore current))
                                 (ok (= 10 check-it:*size*))
                                 '((0 2 1))))))
               (list (trial-observation-arguments (getf result :failure))
                     (when (getf result :shrunk-failure)
                       (trial-observation-arguments (getf result :shrunk-failure)))
                     (getf result :shrink-report))))))
    (let ((first (let ((check-it:*size* 1)) (once)))
          (second (let ((check-it:*size* 99999)) (once))))
      (ok (equal first second)))))

(deftest legacy-and-nested-custom-generators-have-no-false-shrinking-capability
  (let ((*calls* nil) (*pre-calls* 0))
    (let ((result (run-case (lambda () '(10 100 50)) nil)))
      (ok (eq :none (getf (getf result :capabilities) :shrinking)))
      (ok (eq :no-shrinker (getf (getf result :shrink-report) :termination)))
      (ok (null (getf result :shrunk-failure)))))
  (let ((registry (make-hash-table-registry)) (shrinks 0))
    (register-generator
      (make-instance 'custom-generator :name 'nested :function (lambda () '(10 20))
                     :shrinker (lambda (value) (declare (ignore value)) (incf shrinks) '((1 2))))
      registry)
    (let* ((contract (make-instance 'function-spec :name 'mutating-list-target
                                   :argument-specs
                                   (list (list 'value (normalize-spec-form '(list-of integer)
                                                                           :generator 'nested)))
                                   :return-spec 'integer))
           (result (run-generated-test
                     (make-instance 'check-it-backend)
                     (make-function-check-property contract :budget 1)
                     :options (list :registry registry :trials 1))))
      (ok (eq :none (getf (getf result :capabilities) :shrinking)))
      (ok (null (getf result :shrunk-failure)))
      (ok (zerop shrinks)))))

(deftest candidate-buckets-preserve-graph-equality
  (let* ((cycle (list 1))
         (shared (list 2))
         (values (list '(1 2) '(1.0 2) (list shared shared)
                       (list (list 2) (list 2)) #(1 2) "ab")))
    (setf (cdr cycle) cycle)
    (push cycle values)
    (dolist (value values)
      (ok (= (cl-spec/src/backends/check-it::candidate-bucket-key value)
             (cl-spec/src/backends/check-it::candidate-bucket-key
              (cl-spec/src/execution:snapshot-value value)))))
    (ok (not (cl-spec/src/execution:same-value-p (third (rest values))
                                                (fourth (rest values)))))))

(defun graph-target (value)
  (push value *calls*)
  "wrong return")

(deftest visited-candidates-retain-sharing-cycles-and-numeric-types
  (let* ((*calls* nil)
         (cycle (list 1))
         (shared (list 2))
         (values (list 1 1.0 (list shared shared) (list (list 2) (list 2))
                       #(1 2) (make-array 2 :element-type 'bit :initial-contents '(1 0)))))
    (setf (cdr cycle) cycle)
    (push cycle values)
    (let* ((candidates (mapcar #'list values))
           (result (run-case
                    (lambda () '(:initial))
                    (lambda (current)
                      (declare (ignore current))
                      (append candidates (cl-spec/src/execution:snapshot-value candidates)))
                    :target 'graph-target :arguments '((value t)) :pre nil :budget 200)))
      (ok (= (1+ (length values)) (length *calls*)))
      (ok (eq :exhausted (getf (getf result :shrink-report) :termination)))
      (ok (getf result :shrunk-failure)))))

(defun run-case (draw shrinker &key (budget 100) (seed 42)
                                (target 'interval-target)
                                (arguments '((lo (range integer 0 100000))
                                             (hi (range integer 0 100000))
                                             (point (range integer 0 100000))))
                                (pre #'interval-pre))
  (let ((registry (make-hash-table-registry))
         (contract (make-instance 'function-spec :name target :argument-specs arguments
                                  :argument-generator 'correlated :return-spec 'integer
                                  :preconditions (when pre '((interval-pre lo hi point)))
                                  :precondition-function pre))
         (*random-state* (seed->random-state seed)))
    (register-generator (make-instance 'custom-generator :name 'correlated
                                      :function draw :shrinker shrinker) registry)
    (run-generated-test (make-instance 'check-it-backend)
                        (make-function-check-property contract :budget 1)
                        :options (list :registry registry :trials 1 :shrink-budget budget))))
