;;;; tests/key-call-schema-test.lisp
(defpackage #:cl-spec/tests/key-call-schema-test
 (:use #:cl)
 (:import-from #:rove #:deftest #:ok)
 (:import-from #:cl-spec/src/call-schema #:make-call-layout #:normalize-call-declarations
 #:validate-call-declarations #:call-layout-accepts-p #:bind-call-arguments
 #:bound-call-values #:bound-call-presence #:bound-call-arguments #:call-arguments-spec)
 (:import-from #:cl-spec/src/call-validation)
 (:import-from #:cl-spec/src/explain #:compile-node)
 (:import-from #:cl-spec/src/conditions #:invalid-function-spec-form))
(in-package #:cl-spec/tests/key-call-schema-test)
(defun layout (declarations)
 (make-call-layout (normalize-call-declarations declarations)))
(deftest explicit-key-first-occurrence
 (let* ((layout (layout '(&key ((:size size) integer size-p))))
        (raw (list :size nil :size 3))
        (bound (bind-call-arguments layout raw))
        (check (compile-node (make-instance 'call-arguments-spec :layout layout) nil)))
   (ok (eq raw (bound-call-arguments bound)))
   (ok (equal '(nil t) (bound-call-values bound)))
   (ok (equal '(t) (bound-call-presence bound)))
   (ok (equal '(nil nil) (bound-call-values (bind-call-arguments layout nil))))
   (ok (null (funcall check nil nil)))
   (ok (funcall check raw nil))
   (ok (null (funcall check '(:size 3 :size nil) nil)))))
(deftest key-shape-and-control
 (let ((layout (layout '(&key ((:size size) integer)))))
   (dolist (raw '((:unknown 2) (:size) (size 1) (:unknown 2 :allow-other-keys nil
                                                   :allow-other-keys t)))
     (ok (not (call-layout-accepts-p layout raw))))
   (dolist (raw '(nil (:allow-other-keys nil) (:unknown 2 :allow-other-keys t)
                 (:allow-other-keys t :allow-other-keys nil :unknown 2)))
     (ok (call-layout-accepts-p layout raw))))
 (ok (call-layout-accepts-p (layout '(&key &allow-other-keys)) '(:anything 1))))
(deftest key-optional-prefix-is-greedy
 (let ((layout (layout '(&optional (value t value-p) &key ((:size size) integer size-p)))))
   (ok (not (call-layout-accepts-p layout '(:size 2))))
   (ok (equal '(nil t 2 t)
              (bound-call-values (bind-call-arguments layout '(nil :size 2)))))
   (ok (equal '(nil nil nil nil) (bound-call-values (bind-call-arguments layout nil))))))
(deftest malformed-key-declarations
 (dolist (declarations '((&key (size integer)) (&key ((size size) integer))
                        (&key ((:allow-other-keys value) t))
                        (&key ((:size a) t) ((:size b) t))
                        (&key ((:size a) t a)) (&key &optional)
                        (&allow-other-keys) (&key &allow-other-keys ((:size a) t))
                        (&key &key)))
   (ok (handler-case (progn (validate-call-declarations declarations) nil)
         (invalid-function-spec-form () t)))))

(deftest key-paths-and-cyclic-inputs
 (let* ((layout (layout '(&key ((:size size) integer))))
        (check (compile-node (make-instance 'call-arguments-spec :layout layout) nil))
        (cycle (list :size 2)))
   (setf (cddr cycle) cycle)
   (ok (not (call-layout-accepts-p layout cycle)))
   (ok (eq :not-a-list (getf (first (funcall check cycle nil)) :kind)))
   (let ((datum (first (funcall check '(:size nil) nil))))
     (ok (equal '(:args :size) (getf datum :path)))
     (ok (equal '(0) (getf datum :tuple-path))))
   (let ((datum (first (funcall check '(:unexpected nil) nil))))
     (ok (eq :unknown-key (getf datum :kind)))
     (ok (eq :unexpected (getf datum :key)))
     (ok (null (getf datum :tuple-path)))
     (ok (null (getf datum :field-path))))))
