;;;; tests/rest-call-schema-test.lisp
(defpackage #:cl-spec/tests/rest-call-schema-test
 (:use #:cl)
 (:import-from #:rove #:deftest #:ok)
 (:import-from #:cl-spec/src/call-schema #:make-call-layout #:normalize-call-declarations
 #:validate-call-declarations #:call-layout-accepts-p #:bind-call-arguments
 #:bound-call-values #:bound-call-presence #:call-arguments-spec)
 (:import-from #:cl-spec/src/call-validation)
 (:import-from #:cl-spec/src/explain #:compile-node)
 (:import-from #:cl-spec/src/conditions #:invalid-function-spec-form))
(in-package #:cl-spec/tests/rest-call-schema-test)
(defun layout (declarations) (make-call-layout (normalize-call-declarations declarations)))
(deftest rest-whole-tail-and-identity
 (let* ((layout (layout '((first integer) &rest (tail (list-of integer)))))
        (raw (list 1 2 3))
        (bound (bind-call-arguments layout raw))
        (check (compile-node (make-instance 'call-arguments-spec :layout layout) nil)))
   (ok (eq (cdr raw) (second (bound-call-values bound))))
   (ok (equal '(t t) (bound-call-presence bound)))
   (ok (equal '(1 nil) (bound-call-values (bind-call-arguments layout '(1)))))
   (ok (null (funcall check '(1) nil)))
   (ok (null (funcall check raw nil)))
   (ok (funcall check '(1 2 "bad") nil))))
(deftest rest-and-keys-share-tail
 (let* ((layout (layout '(&optional (first t first-p) &rest (tail list)
                         &key ((:size size) integer size-p))))
        (raw (list nil :size 3 :size 4))
        (bound (bind-call-arguments layout raw)))
   (ok (eq (cdr raw) (third (bound-call-values bound))))
   (ok (equal (list nil t (cdr raw) 3 t) (bound-call-values bound)))
   (ok (equal '(t t t) (bound-call-presence bound)))
   (ok (not (call-layout-accepts-p layout '(nil :unknown 3))))))
(deftest rest-shape-and-declaration-errors
 (dolist (declarations '((&rest) (&rest (tail list flag)) (&rest (tail list) (extra t))
                        (&rest (tail list) &rest (other list)) (&key &rest (tail list))
                        ((tail t) &rest (tail list)) (&rest (tail list) &optional (v t))))
   (ok (handler-case (progn (validate-call-declarations declarations) nil)
         (invalid-function-spec-form () t))))
 (let ((layout (layout '(&rest (tail list)))) (cycle (list 1)))
   (setf (cdr cycle) cycle)
   (ok (not (call-layout-accepts-p layout cycle)))
   (ok (not (call-layout-accepts-p layout '(1 . 2))))
   (ok (call-layout-accepts-p layout '(1 2 3)))))

(deftest rest-validates-one-whole-list-including-empty
 (let* ((layout (layout '(&rest (tail (tuple integer string)))))
        (check (compile-node (make-instance 'call-arguments-spec :layout layout) nil)))
   (ok (null (funcall check '(1 "two") nil)))
   (ok (funcall check nil nil))
   (ok (funcall check '(1) nil))
   (ok (funcall check '(1 "two" 3) nil))
   (ok (equal '(:args tail 1) (getf (first (funcall check '(1 2) nil)) :path))))
 (let* ((layout (layout '(&rest (tail list))))
        (nested (list :mutable))
        (raw (list nested))
        (bound (bind-call-arguments layout raw)))
   (ok (eq raw (first (bound-call-values bound))))
   (ok (eq nested (first (first (bound-call-values bound)))))
   (ok (equal '(t) (bound-call-presence (bind-call-arguments layout nil))))))
