;;;; src/utils/artifact-values.lisp
(defpackage #:cl-spec/src/utils/artifact-values
  (:use #:cl)
  (:export #:encode-artifact-value #:decode-artifact-value
           #:serialize-artifact-value #:deserialize-artifact-value
           #:artifact-value-error #:artifact-value-error-reason))
(in-package #:cl-spec/src/utils/artifact-values)

(define-condition artifact-value-error (error)
  ((reason :initarg :reason :reader artifact-value-error-reason
           :documentation "The reason the artifact value was rejected."))
  (:documentation "An unsupported, malformed, or excessive artifact value."))

(defun value-error (reason)
  (error 'artifact-value-error :reason reason))

(defun check-bounds (max-nodes max-depth)
  (unless (and (typep max-nodes '(integer 1 1000000))
               (typep max-depth '(integer 1 256)))
    (value-error :invalid-bounds)))

(defun integer-text (value)
  (when (> (integer-length value) 13000) (value-error :integer-limit))
  (format nil "~D" value))

(defun text-integer (text)
  (unless (and (stringp text) (<= 1 (length text) 4096)
               (let ((start (if (char= (char text 0) #\-) 1 0)))
                 (and (< start (length text))
                      (loop for i from start below (length text)
                            always (digit-char-p (char text i) 10)))))
    (value-error :invalid-integer))
  (parse-integer text :radix 10))

(defun encode-artifact-value (value &key (max-nodes 10000) (max-depth 128))
  "Encode VALUE into a bounded tagged tree; reject sharing and cycles.
Only existing symbols, scalar numbers, characters, simple strings, conses and
simple general vectors are supported. Integers are limited to 13000 bits."
  (check-bounds max-nodes max-depth)
  (let ((seen (make-hash-table :test #'eq)) (nodes 0) (text-size 0))
    (labels ((visit (object depth)
               (when (or (> (incf nodes) max-nodes) (> depth max-depth))
                 (value-error :structure-limit))
               (when (or (consp object) (vectorp object))
                 (when (gethash object seen) (value-error :sharing-or-cycle))
                 (setf (gethash object seen) t))
               ;; Bound aggregate scalar storage before allocating encoded copies.
               (incf text-size
                     (typecase object
                       (string (length object))
                       (symbol (+ (length (symbol-name object))
                                  (if (symbol-package object)
                                      (length (package-name (symbol-package object))) 0)))
                       (integer (integer-length object))
                       (ratio (+ (integer-length (numerator object))
                                 (integer-length (denominator object))))
                       (float 128)
                       (t 0)))
               (when (> text-size 1000000) (value-error :text-limit))
               (typecase object
                 (null (list 0))
                 (symbol
                  (if (eq object t) (list 1)
                      (let ((package (symbol-package object)))
                        (unless (and package
                                     (eq object (find-symbol (symbol-name object) package)))
                          (value-error :unsupported-symbol))
                        (list 2 (copy-seq (package-name package))
                              (copy-seq (symbol-name object))))))
                 (character (list 3 (integer-text (char-code object))))
                 (integer (list 4 (integer-text object)))
                 (ratio (list 5 (integer-text (numerator object))
                              (integer-text (denominator object))))
                 (float
                  (unless (or (typep object 'single-float) (typep object 'double-float))
                    (value-error :unsupported-float))
                  (handler-case
                      (multiple-value-bind (significand exponent sign)
                          (integer-decode-float object)
                        (list 6 (if (typep object 'double-float) 1 0)
                              (integer-text significand) (integer-text exponent)
                              (integer-text sign)))
                    (arithmetic-error () (value-error :unsupported-float))))
                 (simple-string
                  (when (> (length object) 1000000) (value-error :string-limit))
                  (list 7 (copy-seq object)))
                 (cons (list 8 (visit (car object) (1+ depth))
                             (visit (cdr object) (1+ depth))))
                 (simple-vector
                  (when (> (length object) (- max-nodes nodes))
                    (value-error :structure-limit))
                  (cons 9 (loop for element across object collect (visit element (1+ depth)))))
                 (t (value-error :unsupported-value)))))
      (visit value 0))))

(defun decode-artifact-value (data &key (max-nodes 10000) (max-depth 128))
  "Restore a bounded tagged tree without interning symbols or invoking the reader."
  (check-bounds max-nodes max-depth)
  (let ((seen (make-hash-table :test #'eq)) (nodes 0) (cells 0) (text-size 0))
    (labels ((record-fields (record)
               (unless (consp record) (value-error :invalid-record))
               (loop for tail = record then (cdr tail)
                     while tail
                     do (unless (and (consp tail) (not (gethash tail seen))
                                     (<= (incf cells) (* 8 max-nodes)))
                          (value-error :invalid-record))
                        (setf (gethash tail seen) t)
                     collect (car tail)))
             (visit (record depth)
               (when (or (> (incf nodes) max-nodes) (> depth max-depth))
                 (value-error :structure-limit))
               (let* ((fields (record-fields record)) (tag (first fields))
                      (args (rest fields)) (arity (length args)))
                 (unless (and (typep tag '(integer 0 9))
                              (or (= tag 9)
                                  (= arity (nth tag '(0 0 2 1 1 2 4 1 2)))))
                   (value-error :invalid-record))
                 (dolist (argument args)
                   (when (stringp argument) (incf text-size (length argument))))
                 (when (> text-size 1000000) (value-error :text-limit))
                 (case tag
                   (0 nil)
                   (1 t)
                   (2 (unless (every #'stringp args) (value-error :invalid-symbol))
                      (let ((package (find-package (first args))))
                        (unless package (value-error :missing-package))
                        (multiple-value-bind (symbol status) (find-symbol (second args) package)
                          (unless status (value-error :missing-symbol))
                          symbol)))
                   (3 (let* ((code (text-integer (first args)))
                             (character (and (<= 0 code) (< code char-code-limit)
                                             (code-char code))))
                        (or character (value-error :invalid-character))))
                   (4 (text-integer (first args)))
                   (5 (let ((n (text-integer (first args)))
                            (d (text-integer (second args))))
                        (unless (> d 1) (value-error :invalid-ratio))
                        (let ((result (/ n d)))
                          (unless (typep result 'ratio) (value-error :invalid-ratio))
                          result)))
                   (6 (unless (member (first args) '(0 1)) (value-error :invalid-float))
                      (let ((prototype (if (= (first args) 1) 1d0 1f0))
                             (significand (text-integer (second args)))
                             (exponent (text-integer (third args)))
                             (sign (text-integer (fourth args))))
                        (unless (and (<= 0 significand (1- (ash 1 (float-digits prototype))))
                                     (<= -1200 exponent 1200) (member sign '(-1 1)))
                          (value-error :invalid-float))
                        (handler-case
                            (let ((result (* (float sign prototype)
                                             (scale-float (float significand prototype)
                                                          exponent))))
                              (multiple-value-bind (s e sign-value) (integer-decode-float result)
                                (unless (and (= s significand) (= e exponent) (= sign sign-value))
                                  (value-error :invalid-float)))
                              result)
                          (arithmetic-error () (value-error :invalid-float)))))
                   (7 (let ((string (first args)))
                        (unless (and (typep string 'simple-string)
                                     (<= (length string) 1000000))
                          (value-error :invalid-string))
                        (copy-seq string)))
                   (8 (cons (visit (first args) (1+ depth))
                            (visit (second args) (1+ depth))))
                   (9 (when (> arity (- max-nodes nodes)) (value-error :structure-limit))
                      (map 'simple-vector (lambda (item) (visit item (1+ depth))) args))))))
      (visit data 0))))

(defun serialize-artifact-value (value &key (max-chars 1000000)
                                                (max-nodes 10000) (max-depth 128))
  "Serialize VALUE to a restricted, length-prefixed wire format with bounded output."
  (unless (typep max-chars '(integer 1 10000000)) (value-error :invalid-bounds))
  (let ((data (encode-artifact-value value :max-nodes max-nodes :max-depth max-depth))
        (count 0))
    (with-output-to-string (stream)
      (labels ((emit (text)
                 (when (> (incf count (length text)) max-chars) (value-error :character-limit))
                 (write-string text stream))
               (write-data (item)
                 (typecase item
                   (string (emit (format nil "~D:" (length item))) (emit item))
                   (integer (emit (integer-text item)))
                   (cons (emit "(")
                         (loop for tail on item do (write-data (car tail))
                               when (cdr tail) do (emit " "))
                         (emit ")")))))
        (emit "AV1 ")
        (write-data data)))))

(defun deserialize-artifact-value (string &key (max-chars 1000000)
                                                    (max-nodes 10000) (max-depth 128))
  "Parse the AV1 restricted wire format without the Common Lisp reader."
  (check-bounds max-nodes max-depth)
  (unless (and (typep max-chars '(integer 1 10000000)) (stringp string)
               (<= 4 (length string) max-chars) (string= string "AV1 " :end1 4))
    (value-error :invalid-wire))
  (let ((position 4) (size (length string)) (nodes 0))
    (labels ((peek () (and (< position size) (char string position)))
             (spaces () (loop while (eql (peek) #\Space) do (incf position)))
             (parse-data (depth)
               (spaces)
               (when (or (> depth (+ max-depth 1)) (> (incf nodes) (* 8 max-nodes)))
                 (value-error :structure-limit))
               (cond
                 ((eql (peek) #\()
                  (incf position)
                  (let ((items nil))
                    (loop (spaces)
                          (unless (peek) (value-error :invalid-wire))
                          (when (eql (peek) #\)) (incf position) (return (nreverse items)))
                          (push (parse-data (1+ depth)) items))))
                 ((and (peek) (digit-char-p (peek) 10))
                  (let ((number 0) (digits 0))
                    (loop while (and (peek) (digit-char-p (peek) 10))
                          do (when (> (incf digits) 8) (value-error :invalid-wire))
                             (setf number (+ (* number 10) (digit-char-p (peek) 10)))
                             (incf position))
                    (if (eql (peek) #\:)
                        (progn
                          (incf position)
                          (unless (<= number (- size position)) (value-error :invalid-wire))
                          (prog1 (subseq string position (+ position number))
                            (incf position number)))
                        (progn
                          (unless (or (null (peek)) (find (peek) " )"))
                            (value-error :invalid-wire))
                          number))))
                 (t (value-error :invalid-wire)))))
      (let ((data (parse-data 0)))
        (spaces)
        (unless (= position size) (value-error :trailing-data))
        (decode-artifact-value data :max-nodes max-nodes :max-depth max-depth)))))
